AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda CD for CapStone Project
Resources:
  PUTLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./CreateInsertTable
      Description: 'Lambda function to Create Table, Insert, Update and Delete DynamoDB data '
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: "/Dynamo"
            Method: PUT
      Environment:
        Variables:
          REGION: us-east-1
  GETLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./FetchTable
      Description: 'Lambda function to Fetch DynamoDB data'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/Dynamo"
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1
