AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda CD for CapStone Project
Resources:
  LambdaCapStone:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CapStone Project Get and Put request to DynamoDB'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'